title: Data Wave
description: A simulator / Receiver application to send and receive messages using services like IoT Hub, Event Hub, Service Bus and Mqtt
theme: just-the-docs

url: https://gibinfrancis.github.io/DataWave/

aux_links:
  Repository: https://github.com/gibinfrancis/DataWave
